language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
   - git config --global user.name "TravisCI"
   - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
   - source ~/travis-perl-helpers/init
   - build-perl
   - perl -V
   - cpanm -n Devel::Cover::Report::Coveralls Dist::Zilla::Plugin::OSPrereqs
   - cpanm -n Dist::Zilla::Plugin::AutoPrereqs Dist::Zilla::Plugin::AutoVersion Dist::Zilla::Plugin::ConfirmRelease Dist::Zilla::Plugin::Git::Contributors Dist::Zilla::Plugin::OurPkgVersion Dist::Zilla::Plugin::PodSyntaxTests Dist::Zilla::Plugin::ReadmeAnyFromPod Dist::Zilla::Plugin::Test::Perl::Critic Dist::Zilla::Plugin::TestRelease Dist::Zilla::Plugin::UploadToCPAN Dist::Zilla::PluginBundle::Basic
   - cpanm -n Test::More List::Util Capture::Tiny Test::Pod::Coverage Devel::Cover::Report::Coveralls

install:
    - cpanm -n Carp IO::Handle IO::Select JSON English

script: HARNESS_IS_VERBOSE=1 dzil test

after_script:
  - cover -test -make 'prove -Ilib t' -report coveralls

